# Generated by Django 2.2 on 2019-04-07 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=1000)),
                ('height', models.CharField(max_length=4)),
                ('weight', models.CharField(max_length=4)),
                ('reason', models.TextField(max_length=1000)),
                ('prescribed_tablets', models.TextField(blank=True, max_length=1000, null=True)),
                ('drug_allergies', models.TextField(blank=True, max_length=1000, null=True)),
                ('illnesses', multiselectfield.db.fields.MultiSelectField(choices=[('anemia', 'Anemia'), ('asthma', 'Asthma'), ('arthiritis', 'Arthritis'), ('cancer', 'Cancer'), ('gout', 'Gout'), ('diabetes', 'Diabetes'), ('emotional_disorder', 'Emotional Disorder'), ('epilepsy_seizures', 'Epilepsy Seizures'), ('fainting_spells', 'Fainting Spells'), ('gallstones', 'Gallstones'), ('heart_disease', 'Heart Disease'), ('heart_attack', 'Heart Attack'), ('rheumatic_fever', 'Rheumatic Fever'), ('high_blood_pressure', 'High Blood Pressure'), ('digestive_problems', 'Digestive Problems'), ('ulcerative_colitis', 'Ulcerative Colitis'), ('ulcer_disease', 'Ulcer Disease'), ('hepatitis', 'Hepatitis'), ('kidney_disease', 'Kidney Disease'), ('liver_disease', 'Liver Disease'), ('sleep_apnea', 'Sleep Apnea'), ('use_a_c_pap_machine', 'Use a C-PAP machine'), ('thyroid_problems', 'Thyroid Problems'), ('tuberculosis', 'Tuberculosis'), ('venereal_disease', 'Venereal Disease'), ('neurological_disorders', 'Neurological Disorders'), ('bleeding_disorders', 'Bleeding Disorders'), ('lung_disease', 'Lung Disease'), ('emphysema', 'Emphysema')], max_length=4000)),
                ('other_illnesses', models.TextField(blank=True, max_length=1000, null=True)),
                ('operations', models.TextField(blank=True, max_length=1000, null=True)),
                ('current_medications', models.TextField(blank=True, max_length=1000, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('address', models.CharField(max_length=1000)),
                ('qualification', models.CharField(choices=[('MD', 'MD'), ('MS', 'MS'), ('MBBS', 'MBBS'), ('BDS', 'BDS'), ('Other', 'Other')], max_length=100)),
                ('designation', models.CharField(choices=[('Neurologist', 'Neurologist'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Surgeon', 'Surgeon'), ('Veterinarian', 'Veterinarian'), ('Homeopathic Doctor', 'Homeopathic Doctor'), ('Physiotherapist', 'Physiotherapist'), ('Dermatologist', 'Dermatologist'), ('Cardiologist', 'Cardiologist'), ('Gynecologist', 'Gynecologist'), ('Other', 'Other')], max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
