# Generated by Django 2.2 on 2019-04-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='is_approved_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='is_open_for_appointment',
            field=models.BooleanField(default=True),
        ),
    ]
