# Generated by Django 2.2 on 2019-04-07 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('userprofile', '0002_auto_20190407_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='user_social',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount'),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='user_social',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount'),
        ),
    ]
