# Generated by Django 2.2 on 2019-04-07 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20190407_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='patients_diagnosed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.PatientModel'),
        ),
    ]
