# Generated by Django 2.2 on 2019-04-07 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_doctormodel_patients_diagnosed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormodel',
            name='patients_diagnosed',
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='diagnosed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.DoctorModel'),
        ),
    ]
